// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities
{
    public partial class GetPostResult
    {
        public int post_id { get; set; }
        public int? user_id { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public string image_url { get; set; }
    }
}
