// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Entities
{
    public partial class GetUserByUsernameResult
    {
        public int user_id { get; set; }
        public string username { get; set; }
        public string email { get; set; }
    }
}
