// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Reply
{
    public int ReplyId { get; set; }

    public int? CommentId { get; set; }

    public int? UserId { get; set; }

    public string Content { get; set; }

    public virtual Comment Comment { get; set; }

    public virtual User User { get; set; }
}